### ISSUE TITLE
Convolution

### ISSUE THREAD

**Issue by JuneToJuly** [Luc-Olsthoorn/TrueShot#2]
We need to test that we get the same values for our type of convolution against Matlab vector convolution.

**Comment by JuneToJuly** [comment]
Ugh. There is no convolution support at the moment for the Nd4j library. Looking at maybe calling some python code from java using a library called `jython`. We could perhaps write our own convolution method though, it doesn't seem that difficult. Just probably won't be very optimized.

**Comment by UFWestlife** [comment]
Hi Ian @JuneToJuly , about the converting process of `byte[] -> double[]` , I wanna describe my understanding first. The input of the converting function is a `double[]` and a `short[]`. I need to transfer each double value to two byte values as the left channel, then convert each short value to a two-byte value as right channel. Four bytes is a loop, finally output the whole `byte[]`.  
  
If my understanding is right, I would say that may be unreachable. Because in the function `byte[]toDoube[]`, the last operation to get the double value is to do a `|` operation between two byte values:  

> temp = (double) ((byteBuffer.get() & 0xff) | (byteBuffer.get() << 8));

While, after some other operations with the value in double[] to get demanded 3D effect, we obtain a new double[] as the input. But, for every double value *`temp`* inside, there are so many pairs of byte value can get the result `a | b == temp`. I think we cannot get a fixed byte value of *a* and *b*, cause there are so many possibilities.  
Above is just my opinion about what's going on now, please point out if I misunderstand something or there are some other ways to achieve it. I will keep doing.

**Comment by JuneToJuly** [comment]
I'll read this over tomorrow morning Zun to make sure I can give you a good answer!

**Comment by JuneToJuly** [comment]
Morning Zun @UFWestlife, So one thing to remember is even though we have two channels, *left* and *right*, we are only going to use the sample data from one, in our case the left. We just copy the 3d sound data from the left to the right. I think this is where you maybe be getting confused.

A sample looks like this in memory:
> *Left First Byte* | *Left Second Byte* | *Right First Byte* | *Right Second Byte*

So, what we are doing for converting the sample to its double form is the following:
* Each sample is four bytes
* We only grab the first two bytes of the sample -- the left channel
* Because these bytes are in little endian order, we have to swap their order before converting to a double  `((byteBuffer.get() & 0xff) | (byteBuffer.get() << 8));`
This grabs the first byte, then shifts the second byte over 8 bits putting in front of the first byte we grabbed. We bit-wise OR the two and we have both bytes in the correct order. When we look at the double value it looks like this:

> *Technically Second Byte* | *Technically First byte* | 0 | 0 | 0 | 0 | 0 | 0

Next we we have to normalize that value which ensures that it is between `-1 and 1` by dividing by 32678. When we do our convolution we will see that we we end up with some new double values which should also be in this range.

We are then going to de-normalize the convoluted values by multiplying by 32678. We will then convert the double back to the two bytes:
* Grab the *Technically Second* and add it to the buffer. If using byte buffer call put()
* Grab the *Technically First Byte* and add it to the buffer. 

We then have our *left* channel. Because we didn't do anything for the right channel. Just do this one more time for the *right* channel and we have our sample!

The values should be in the same order we got them but just two copies of left channel, Sample one:

> *Technically First byte* | *Technically Second Byte* |   *Technically First byte* | *Technically Second Byte* |


Does this help? If not I can chat sometime online if you need.

**Comment by UFWestlife** [comment]
Good morning Ian @JuneToJuly ! Thanks sooo much for your patience and detailed explanation!! You know what, I mixed up the word *REVERSE* and *CONVERT* in the post last late night!! But that doesn't matter because you did make everything clear to me now!!  
Again, really thank you Ian! I will work this out!

**Comment by JuneToJuly** [comment]
Linear convolution is solved. I have verified that it gives the same values as the Matlab equivalent function `conv()`. Moving convolution into a util class.
