### ISSUE TITLE
Convolution Not Working For High Precision Numbers.

### ISSUE THREAD

**Issue by JuneToJuly** [Luc-Olsthoorn/TrueShot#3]
So, the very basic test example for convolution works fine. It seems that for our complex samples, we are having some problems though. The 3D Sound works, it just has some noise.

##### Possible Solution, using the `BigDecimal` class.

**Comment by UFWestlife** [comment]
Good late night Ian! I have a very small suggestion here~ Does the basic "bleep" sound which will be used in our project works fine? If so (or with acceptable noise), I think we have already reached the requirements of HW3.  Because we only need to load a sound file that will be used for the project and convert it to 3D sound with user input (x, y, z). TA will not deduct the points if we implemented every part. For the further research to deal with complex samples, we can do it together during our project. What do you think about this?   Thank you so much for your hard work!!

**Comment by JuneToJuly** [comment]
Zun, you are right, we will worry about this later. I will test with the basic bleep sound to make sure it works and let you know. I assume it will work fine.

**Comment by JuneToJuly** [comment]
Okay, I think I figured this out... The sample rate for the sound file where I was getting some clipping was 48kHz. I think this may have been the problem.
